# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Portfolio de Emma GRAVE"
email: graveemma842@gmail.com
description: "Découvrez mes projets de développement et mon parcours dans le domaine de l'informatique"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: emmagrave
# Infos personnelles (ajouter des champs personnalisés si nécessaire)
author: "Emma GRAVE"
location: "France"
# SEO settings
seo:
  title: "Portfolio de Emma GRAVE"
  description: "Portfolio professionnel de Emma GRAVE - Etudiante en informatique"

# Social links (facile à utiliser dans les templates)
social:
  - title: "github"
    url: "https://github.com/emmagrave"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/emma-grave/"
  - title: "email"
    url: "mailto:graveemma842@gmail.com"



# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
